### ISSUE TITLE
TADTool in Genome wide study

### ISSUE THREAD

**Issue by LeonardoLed** [vaquerizaslab/tadtool#10]
Hello, 
I want to run tadtool in a chromosome full, but come in my mind if there is a default cutoff in order to get TADs, indepently of several parameters like a resolution of my matrix, size of windows to get bins, number of reads before to get my matrix.  
Or if there is a standard way to get fine tunning, because the number of tads can be different if I modify size of windows smaller or if change the cuttoff (index of Insulation Score).

10% of Chr1 
![image](https://user-images.githubusercontent.com/33387734/32851919-090cfda6-c9fc-11e7-8688-dea13a45bf76.png)

Full Chr1
![image](https://user-images.githubusercontent.com/33387734/32852047-6f661358-c9fc-11e7-9aa9-5fc9411a52b7.png)

In a first instance, I could say that the avarage is good paramater to get TADs, but possibly not.  
TADtools is designed to only get TADs in a specfic region?  or is possible study a full chromosome?

Thank you 
Reggards.

**Comment by vaquerizaslab-old** [comment]
Hi there,

first let me make sure I understand all your questions correctly:

1. Is there a default set of parameters, independent of matrix properties, that will result in "good" TAD calls?
2. What is the best way to fine-tune the TAD-calling parameters?
3. Can I use TADtool to call TADs on an entire chromosome?

**Regarding 1**: The TAD-calling parameters that will produce robust TADs depend on a variety of matrix properties, including bin size, coverage, genome, and normalisation method. TADtool was built because there is no "golden" set of parameters that will work in every scenario.

**Regarding 2**: TADtool should help you find **robust** sets of parameters for TAD-calling. A robust parameter set is one where you can change the values slightly in any direction, and they will still give you roughly the same TADs. If you find that your TAD calls vary a lot when "fine-tuning" parameter changes, then those parameters are not robust and you should look for a different parameter range. In the example you posted, the chosen window size is very small, and you would probably get more robust calls with a larger window size.
Additionally, but I am only guessing from the plots you are showing, it looks like your matrix resolution is too big to get any meaningful TADs. A good resolution would be better than 50kb.

**Regarding 3**: It is definitely possible to call TADs on a whole chromosome using TADtool. The procedure we suggest is the following: Start from a normalised matrix of a whole chromosome (<50kb resolution) and use the `tadtool subset` command to extract a smaller region. Typically, any 1-3Mb region with TADs that are nicely visible will do. Then run `tadtool plot` on the matrix subset and choose robust parameters (see above). Note down the parameters you found and run `tadtool tads` on the whole chromosome matrix to extract TADs for the entire chromosome.

I hope that this clarifies things for you.

**Comment by LeonardoLed** [comment]
I will do that, thanks a lot
